apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
spec:
  selector:
    matchLabels:
      run: mynginx
  replicas: 2
  template:
    metadata:
      labels:
        run: mynginx
    spec:
      containers:
      - name: mynginx
        image: mynginx
        ports:
        - containerPort: 80
apiVersion: v1
kind: Service
metadata:
  name: mynginx
spec:
  selector:
    run: mynginx
  ports:
  - port: 5080
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
