apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: nginxwebserver
build:
  artifacts:
    - image: mynginx
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s-pod.yaml
